name: Canary Release

on:
  workflow_dispatch:

jobs:
  canary:
    name: Publish Canary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.3.2"

      - name: Install Dependencies
        run: bun install

      - name: Build project
        run: bun run build --filter @marceloterreiro/flash-calendar

      - name: Version packages (snapshot)
        run: bun changeset version --snapshot canary

      - name: Publish canary to npm
        run: bun changeset publish --tag canary
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
